# Generated by Django 5.1.1 on 2024-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='dependences',
            field=models.ManyToManyField(through='myapp.BusinessDependence', to='myapp.dependence'),
        ),
    ]
